from PySide6.QtWidgets import QWidget,QMainWindow,QLabel,QPushButton,QVBoxLayout,QHBoxLayout,QScrollArea
from PySide6.QtGui import QPixmap,QIcon,QTextOption
from PySide6.QtCore import Qt

import Android_Kitaplar_Paths,C_Kitaplar_Paths,Cpp_Kitaplar_Paths,Data_Structure_Kitaplar_Paths
import DBSM_kitaplar_Paths,HTML_Kitaplar_Paths,Java_Kitaplar_Paths,Python_Kitaplar_Paths
import QA_Kitaplar_Paths,SQL_Kitaplar_Paths,OOP_Kitaplar_Paths
class Widget(QMainWindow):

    def __init__(self):
        super().__init__()
        
        self.scroll = QScrollArea()
        self.widget = QWidget() 
        genel_raflar = QVBoxLayout()
        genel_raflar.setAlignment(Qt.AlignmentFlag.AlignTop)
        self.setWindowTitle("Amal Hawks Kütüphane")
        self.setWindowIcon(QIcon("C:\Yazılım_E-Kitaplar\Logomuz.jpg"))
        self.scroll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll.setWidgetResizable(True)
        self.setGeometry(100,80,1000,700)
        
        # android bölümü
        android_raf = QVBoxLayout()
        android_raf_uzunluk = QHBoxLayout()
        android_raf_adı = QLabel("Android")
        android_kitap_1 = QPushButton()
        android_kitap_1_ad = QLabel("Short Notes",android_kitap_1)
        android_kitap_1_ad.setWordWrap(True)
        android_kitap_1_ad.setFixedSize(90,135)
        android_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        android_kitap_1.setFixedSize(90,135)
        android_kitap_1.clicked.connect(Android_Kitaplar_Paths.android_kitap_1)
        android_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        android_raf_uzunluk.addWidget(android_kitap_1)
        android_raf.addWidget(android_raf_adı)
        android_raf.addLayout(android_raf_uzunluk)
        # c bölümü
        c_raf = QVBoxLayout()
        c_raf_uzunluk = QHBoxLayout()
        c_raf_adı = QLabel("C")
        c_kitap_1 = QPushButton()
        c_kitap_1_ad = QLabel("Sorular Kolay",c_kitap_1)
        c_kitap_1_ad.setWordWrap(True)
        c_kitap_1_ad.setFixedSize(90,135)
        c_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        c_kitap_1.setFixedSize(90,135)
        c_kitap_1.clicked.connect(C_Kitaplar_Paths.c_kitap_1)
        c_kitap_2 = QPushButton()
        c_kitap_2_ad = QLabel("Long Notes",c_kitap_2)
        c_kitap_2_ad.setWordWrap(True)
        c_kitap_2_ad.setFixedSize(90,135)
        c_kitap_2_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        c_kitap_2.setFixedSize(90,135)
        c_kitap_2.clicked.connect(C_Kitaplar_Paths.c_kitap_2)
        c_kitap_3 = QPushButton()
        c_kitap_3_adı = QLabel("Short Loops Notes",c_kitap_3)
        c_kitap_3_adı.setFixedSize(90,135)
        c_kitap_3_adı.setWordWrap(True)
        c_kitap_3_adı.setAlignment(Qt.AlignmentFlag.AlignCenter)
        c_kitap_3.setFixedSize(90,135)
        c_kitap_3.clicked.connect(C_Kitaplar_Paths.c_kitap_3)
        c_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        c_raf_uzunluk.addWidget(c_kitap_1)
        c_raf_uzunluk.addWidget(c_kitap_2)
        c_raf_uzunluk.addWidget(c_kitap_3)
        c_raf.addWidget(c_raf_adı)
        c_raf.addLayout(c_raf_uzunluk) 
        # C++
        cpp_raf = QVBoxLayout()
        cpp_raf_uzunluk = QHBoxLayout()
        cpp_raf_adı = QLabel("C++")
        cpp_kitap_1 = QPushButton()
        cpp_kitap_1_ad = QLabel("Short Notes",cpp_kitap_1)
        cpp_kitap_1_ad.setWordWrap(True)
        cpp_kitap_1_ad.setFixedSize(90,135)
        cpp_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        cpp_kitap_1.setFixedSize(90,135)
        cpp_kitap_1.clicked.connect(Cpp_Kitaplar_Paths.cpp_kitap_1)
        cpp_kitap_2 = QPushButton()
        cpp_kitap_2_ad = QLabel("Intermediate Notes",cpp_kitap_2)
        cpp_kitap_2_ad.setWordWrap(True)
        cpp_kitap_2_ad.setFixedSize(90,135)
        cpp_kitap_2_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        cpp_kitap_2.setFixedSize(90,135)
        cpp_kitap_2.clicked.connect(Cpp_Kitaplar_Paths.cpp_kitap_2)
        cpp_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        cpp_raf_uzunluk.addWidget(cpp_kitap_1)
        cpp_raf_uzunluk.addWidget(cpp_kitap_2)
        cpp_raf.addWidget(cpp_raf_adı)
        cpp_raf.addLayout(cpp_raf_uzunluk)
        
        #Data Structure
        data_structure_raf = QVBoxLayout()
        data_structure_raf_uzunluk = QHBoxLayout()
        data_structure_raf_adı = QLabel("Data Structure")
        data_structure_kitap_1 = QPushButton()
        data_structure_kitap_1_ad = QLabel("Notes",data_structure_kitap_1)
        data_structure_kitap_1_ad.setWordWrap(True)
        data_structure_kitap_1_ad.setFixedSize(90,135)
        data_structure_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        data_structure_kitap_1.setFixedSize(90,135)
        data_structure_kitap_1.clicked.connect(Data_Structure_Kitaplar_Paths.ds_kitap_1)
        data_structure_kitap_2 = QPushButton()
        data_structure_kitap_2_ad = QLabel("Short Notes",data_structure_kitap_2)
        data_structure_kitap_2_ad.setWordWrap(True)
        data_structure_kitap_2_ad.setFixedSize(90,135)
        data_structure_kitap_2_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        data_structure_kitap_2.setFixedSize(90,135)
        data_structure_kitap_2.clicked.connect(Data_Structure_Kitaplar_Paths.ds_kitap_2)
        data_structure_kitap_3 = QPushButton()
        data_structure_kitap_3_adı = QLabel("Stack Short Notes",data_structure_kitap_3)
        data_structure_kitap_3_adı.setFixedSize(90,135)
        data_structure_kitap_3_adı.setWordWrap(True)
        data_structure_kitap_3_adı.setAlignment(Qt.AlignmentFlag.AlignCenter)
        data_structure_kitap_3.setFixedSize(90,135)
        data_structure_kitap_3.clicked.connect(Data_Structure_Kitaplar_Paths.ds_kitap_3)
        data_structure_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        data_structure_raf_uzunluk.addWidget(data_structure_kitap_1)
        data_structure_raf_uzunluk.addWidget(data_structure_kitap_2)
        data_structure_raf_uzunluk.addWidget(data_structure_kitap_3)
        data_structure_raf.addWidget(data_structure_raf_adı)
        data_structure_raf.addLayout(data_structure_raf_uzunluk)
        #DBSM
        dbsm_raf = QVBoxLayout()
        dbsm_raf_uzunluk = QHBoxLayout()
        dbsm_raf_adı = QLabel("DBSM")
        dbsm_kitap_1 = QPushButton()
        dbsm_kitap_1_adı = QLabel("DBSM Normalization",dbsm_kitap_1)
        dbsm_kitap_1_adı.setWordWrap(True)
        dbsm_kitap_1_adı.setFixedSize(90,135)
        dbsm_kitap_1.setFixedSize(90,135)
        dbsm_kitap_1_adı.setAlignment(Qt.AlignmentFlag.AlignCenter)
        dbsm_kitap_1.clicked.connect(DBSM_kitaplar_Paths.dbsm_kitap_1)
        dbsm_kitap_2 = QPushButton()
        dbsm_kitap_2_adı = QLabel("Long Notes",dbsm_kitap_2)
        dbsm_kitap_2_adı.setWordWrap(True)
        dbsm_kitap_2_adı.setFixedSize(90,135)
        dbsm_kitap_2_adı.setAlignment(Qt.AlignmentFlag.AlignCenter)
        dbsm_kitap_2.setFixedSize(90,135)
        dbsm_kitap_2.clicked.connect(DBSM_kitaplar_Paths.dbsm_kitap_2)
        dbsm_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        dbsm_raf_uzunluk.addWidget(dbsm_kitap_1)
        dbsm_raf_uzunluk.addWidget(dbsm_kitap_2)
        dbsm_raf.addWidget(dbsm_raf_adı)
        dbsm_raf.addLayout(dbsm_raf_uzunluk)
        #HTML 
        html_raf = QVBoxLayout()
        html_raf_uzunluk = QHBoxLayout()
        html_raf_adı = QLabel("HTML")
        html_kitap_1 = QPushButton()
        html_kitap_1_ad = QLabel("Long Notes",html_kitap_1)
        html_kitap_1_ad.setWordWrap(True)
        html_kitap_1_ad.setFixedSize(90,135)
        html_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        html_kitap_1.setFixedSize(90,135)
        html_kitap_1.clicked.connect(HTML_Kitaplar_Paths.html_kitap_1)
        html_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        html_raf_uzunluk.addWidget(html_kitap_1)
        html_raf.addWidget(html_raf_adı)
        html_raf.addLayout(html_raf_uzunluk)
        #Java
        java_raf = QVBoxLayout()
        java_raf_uzunluk = QHBoxLayout()
        java_raf_adı = QLabel("Java")
        java_kitap_1 = QPushButton()
        java_kitap_1_ad = QLabel("Sorular Kolay",java_kitap_1)
        java_kitap_1_ad.setWordWrap(True)
        java_kitap_1_ad.setFixedSize(90,135)
        java_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        java_kitap_1.setFixedSize(90,135)
        java_kitap_1.clicked.connect(Java_Kitaplar_Paths.java_kitap_1)
        java_kitap_2 = QPushButton()
        java_kitap_2_ad = QLabel("Short Notes",java_kitap_2)
        java_kitap_2_ad.setWordWrap(True)
        java_kitap_2_ad.setFixedSize(90,135)
        java_kitap_2_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        java_kitap_2.setFixedSize(90,135)
        java_kitap_2.clicked.connect(Java_Kitaplar_Paths.java_kitap_2)
        java_kitap_3 = QPushButton()
        java_kitap_3_ad = QLabel(" İleri Seviye E-Book ",java_kitap_3)
        java_kitap_3_ad.setWordWrap(True)
        java_kitap_3_ad.setFixedSize(90,135)
        java_kitap_3_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        java_kitap_3.setFixedSize(90,135)
        java_kitap_3.clicked.connect(Java_Kitaplar_Paths.java_kitap_3)
        java_kitap_4 = QPushButton()
        java_kitap_4_ad = QLabel("Long Notes",java_kitap_4)
        java_kitap_4_ad.setWordWrap(True)
        java_kitap_4_ad.setFixedSize(90,135)
        java_kitap_4_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        java_kitap_4.setFixedSize(90,135)
        java_kitap_4.clicked.connect(Java_Kitaplar_Paths.java_kitap_4)
        java_kitap_5 = QPushButton()
        java_kitap_5_ad = QLabel("Sorular Zor",java_kitap_5)
        java_kitap_5_ad.setWordWrap(True)
        java_kitap_5_ad.setFixedSize(90,135)
        java_kitap_5_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        java_kitap_5.setFixedSize(90,135)
        java_kitap_5.clicked.connect(Java_Kitaplar_Paths.java_kitap_5)
        java_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        java_raf_uzunluk.addWidget(java_kitap_1)
        java_raf_uzunluk.addWidget(java_kitap_2)
        java_raf_uzunluk.addWidget(java_kitap_3)
        java_raf_uzunluk.addWidget(java_kitap_4)
        java_raf_uzunluk.addWidget(java_kitap_5)
        java_raf.addWidget(java_raf_adı)
        java_raf.addLayout(java_raf_uzunluk)
        
        #OOP
        oop_raf = QVBoxLayout()
        oop_raf_uzunluk = QHBoxLayout()
        oop_raf_adı = QLabel("OOP (Object Oriented Progamming)")
        oop_kitap_1 = QPushButton()
        oop_kitap_1_ad = QLabel("OOP Concepts",oop_kitap_1)
        oop_kitap_1_ad.setWordWrap(True)
        oop_kitap_1_ad.setFixedSize(90,135)
        oop_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        oop_kitap_1.setFixedSize(90,135)
        oop_kitap_1.clicked.connect(OOP_Kitaplar_Paths.oop_kitap_1)
        oop_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        oop_raf_uzunluk.addWidget(oop_kitap_1)
        oop_raf.addWidget(oop_raf_adı)
        oop_raf.addLayout(oop_raf_uzunluk)

        #Python 
        python_raf = QVBoxLayout()
        python_raf_uzunluk = QHBoxLayout()
        python_raf_adı = QLabel("Python")
        python_kitap_1 = QPushButton()
        python_kitap_1_ad = QLabel("Orta Seviye E-Book",python_kitap_1)
        python_kitap_1_ad.setWordWrap(True)
        python_kitap_1_ad.setFixedSize(90,135)
        python_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        python_kitap_1.setFixedSize(90,135)
        python_kitap_1.clicked.connect(Python_Kitaplar_Paths.python_kitap_1)
        python_kitap_2 = QPushButton()
        python_kitap_2_ad = QLabel("Operators Short Notes",python_kitap_2)
        python_kitap_2_ad.setWordWrap(True)
        python_kitap_2_ad.setFixedSize(90,135)
        python_kitap_2_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        python_kitap_2.setFixedSize(90,135)
        python_kitap_2.clicked.connect(Python_Kitaplar_Paths.python_kitap_2)
        python_kitap_3 = QPushButton()
        python_kitap_3_ad = QLabel("Game Dev With Python",python_kitap_3)
        python_kitap_3_ad.setWordWrap(True)
        python_kitap_3_ad.setFixedSize(90,135)
        python_kitap_3_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        python_kitap_3.setFixedSize(90,135)
        python_kitap_3.clicked.connect(Python_Kitaplar_Paths.python_kitap_3)
        python_kitap_4 = QPushButton()
        python_kitap_4_ad = QLabel("Long Notes",python_kitap_4)
        python_kitap_4_ad.setWordWrap(True)
        python_kitap_4_ad.setFixedSize(90,135)
        python_kitap_4_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        python_kitap_4.setFixedSize(90,135)
        python_kitap_4.clicked.connect(Python_Kitaplar_Paths.python_kitap_4)
        python_kitap_5 = QPushButton()
        python_kitap_5_ad = QLabel("Short Notes",python_kitap_5)
        python_kitap_5_ad.setWordWrap(True)
        python_kitap_5_ad.setFixedSize(90,135)
        python_kitap_5_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        python_kitap_5.setFixedSize(90,135)
        python_kitap_5.clicked.connect(Python_Kitaplar_Paths.python_kitap_5)
        python_kitap_6 = QPushButton()
        python_kitap_6_ad = QLabel("Sorular Zor",python_kitap_6)
        python_kitap_6_ad.setWordWrap(True)
        python_kitap_6_ad.setFixedSize(90,135)
        python_kitap_6_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        python_kitap_6.setFixedSize(90,135)
        python_kitap_6.clicked.connect(Python_Kitaplar_Paths.python_kitap_6)
        python_kitap_7 = QPushButton()
        python_kitap_7_ad = QLabel("Sorular Kolay",python_kitap_7)
        python_kitap_7_ad.setWordWrap(True)
        python_kitap_7_ad.setFixedSize(90,135)
        python_kitap_7_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)   
        python_kitap_7.setFixedSize(90,135)
        python_kitap_7.clicked.connect(Python_Kitaplar_Paths.python_kitap_7)
        python_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        python_raf_uzunluk.addWidget(python_kitap_1)
        python_raf_uzunluk.addWidget(python_kitap_2)
        python_raf_uzunluk.addWidget(python_kitap_3)
        python_raf_uzunluk.addWidget(python_kitap_4)
        python_raf_uzunluk.addWidget(python_kitap_5)
        python_raf_uzunluk.addWidget(python_kitap_6)
        python_raf_uzunluk.addWidget(python_kitap_7)
        python_raf.addWidget(python_raf_adı)
        python_raf.addLayout(python_raf_uzunluk)
        #Q&A
        qa_raf = QVBoxLayout()
        qa_raf_uzunluk = QHBoxLayout()
        qa_raf_adı = QLabel("Q&A")
        qa_kitap_1 = QPushButton()
        qa_kitap_1_ad = QLabel("En Yakın Zamanda Silincek",qa_kitap_1)
        qa_kitap_1_ad.setWordWrap(True)
        qa_kitap_1_ad.setFixedSize(90,135)
        qa_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        qa_kitap_1.setFixedSize(90,135)
        qa_kitap_1.clicked.connect(QA_Kitaplar_Paths.qa_kitap_1)
        qa_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        qa_raf_uzunluk.addWidget(qa_kitap_1)
        qa_raf.addWidget(qa_raf_adı)
        qa_raf.addLayout(qa_raf_uzunluk)
        #SQL
        sql_raf = QVBoxLayout()
        sql_raf_uzunluk = QHBoxLayout()
        sql_raf_adı = QLabel("SQL")
        sql_kitap_1 = QPushButton()
        sql_kitap_1_ad = QLabel("Short Notes",sql_kitap_1)
        sql_kitap_1_ad.setWordWrap(True)
        sql_kitap_1_ad.setFixedSize(90,135)
        sql_kitap_1_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_1.setFixedSize(90,135)        
        sql_kitap_1.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_1)
        sql_kitap_2 = QPushButton()
        sql_kitap_2_ad = QLabel("SQL Commands",sql_kitap_2)
        sql_kitap_2_ad.setWordWrap(True)
        sql_kitap_2_ad.setFixedSize(90,135)
        sql_kitap_2_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_2.setFixedSize(90,135)
        sql_kitap_2.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_2)
        sql_kitap_3 = QPushButton()
        sql_kitap_3_ad = QLabel("Sorular",sql_kitap_3)
        sql_kitap_3_ad.setWordWrap(True)
        sql_kitap_3_ad.setFixedSize(90,135)
        sql_kitap_3_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_3.setFixedSize(90,135)
        sql_kitap_3.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_3)
        sql_kitap_4 = QPushButton()
        sql_kitap_4_ad = QLabel("JOIN Short Notes",sql_kitap_4)
        sql_kitap_4_ad.setWordWrap(True)
        sql_kitap_4_ad.setFixedSize(90,135)
        sql_kitap_4_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_4.setFixedSize(90,135)
        sql_kitap_4.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_4)
        sql_kitap_5 = QPushButton()
        sql_kitap_5_ad = QLabel("Short Constraints Notes 3",sql_kitap_5)
        sql_kitap_5_ad.setWordWrap(True)
        sql_kitap_5_ad.setFixedSize(90,135)
        sql_kitap_5_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_5.setFixedSize(90,135)
        sql_kitap_5.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_5)
        sql_kitap_6 = QPushButton()
        sql_kitap_6_ad = QLabel("Short Notes 2",sql_kitap_6)
        sql_kitap_6_ad.setWordWrap(True)
        sql_kitap_6_ad.setFixedSize(90,135)
        sql_kitap_6_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_6.setFixedSize(90,135)
        sql_kitap_6.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_6)
        sql_kitap_7 = QPushButton()
        sql_kitap_7_ad = QLabel("Short Constraints Notes 1 2",sql_kitap_7)
        sql_kitap_7_ad.setWordWrap(True)
        sql_kitap_7_ad.setFixedSize(90,135)
        sql_kitap_7_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_7.setFixedSize(90,135)
        sql_kitap_7.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_7)
        sql_kitap_8 = QPushButton()
        sql_kitap_8_ad = QLabel("SQL Quaries",sql_kitap_8)
        sql_kitap_8_ad.setWordWrap(True)
        sql_kitap_8_ad.setFixedSize(90,135)
        sql_kitap_8_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_8.setFixedSize(90,135)
        sql_kitap_8.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_8)
        sql_kitap_9 = QPushButton()
        sql_kitap_9_ad = QLabel("SQL Views",sql_kitap_9)
        sql_kitap_9_ad.setWordWrap(True)
        sql_kitap_9_ad.setFixedSize(90,135)
        sql_kitap_9_ad.setAlignment(Qt.AlignmentFlag.AlignCenter)  
        sql_kitap_9.setFixedSize(90,135)
        sql_kitap_9.clicked.connect(SQL_Kitaplar_Paths.sql_kitap_9)
        sql_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        sql_raf_uzunluk.addWidget(sql_kitap_1)
        sql_raf_uzunluk.addWidget(sql_kitap_2)
        sql_raf_uzunluk.addWidget(sql_kitap_3)
        sql_raf_uzunluk.addWidget(sql_kitap_4)
        sql_raf_uzunluk.addWidget(sql_kitap_5)
        sql_raf_uzunluk.addWidget(sql_kitap_6)
        sql_raf_uzunluk.addWidget(sql_kitap_7)
        sql_raf_uzunluk.addWidget(sql_kitap_8)
        sql_raf_uzunluk.addWidget(sql_kitap_9)
        sql_raf.addWidget(sql_raf_adı)
        sql_raf.addLayout(sql_raf_uzunluk)
        #FRC
        frc_raf = QVBoxLayout()
        frc_raf_uzunluk = QHBoxLayout()
        frc_raf_adı = QLabel("FRC")
        frc_kitap_1 = QPushButton(text="Gelecek")
        frc_kitap_1.setFixedSize(90,135)
        frc_kitap_2 = QPushButton(text="Gelecek")
        frc_kitap_2.setFixedSize(90,135)
        frc_kitap_3 = QPushButton(text="Gelecek")
        frc_kitap_3.setFixedSize(90,135)
        frc_kitap_4 = QPushButton(text="Gelecek")
        frc_kitap_4.setFixedSize(90,135)
        frc_kitap_5 = QPushButton(text="Gelecek")
        frc_kitap_5.setFixedSize(90,135)
        frc_kitap_6 = QPushButton(text="Gelecek")
        frc_kitap_6.setFixedSize(90,135)
        frc_raf_uzunluk.setAlignment(Qt.AlignmentFlag.AlignLeft)
        frc_raf_uzunluk.addWidget(frc_kitap_1)
        frc_raf_uzunluk.addWidget(frc_kitap_2)
        frc_raf_uzunluk.addWidget(frc_kitap_3)
        frc_raf_uzunluk.addWidget(frc_kitap_4)
        frc_raf_uzunluk.addWidget(frc_kitap_5)
        frc_raf_uzunluk.addWidget(frc_kitap_6)
        frc_raf.addWidget(frc_raf_adı)
        frc_raf.addLayout(frc_raf_uzunluk)
        #Genel Raflar Tanımlama
        genel_raflar.addLayout(android_raf)
        genel_raflar.addLayout(c_raf)
        genel_raflar.addLayout(cpp_raf)
        genel_raflar.addLayout(data_structure_raf)
        genel_raflar.addLayout(dbsm_raf)
        genel_raflar.addLayout(html_raf)
        genel_raflar.addLayout(java_raf)
        genel_raflar.addLayout(oop_raf)
        genel_raflar.addLayout(python_raf)
        genel_raflar.addLayout(qa_raf)
        genel_raflar.addLayout(sql_raf)
        genel_raflar.addLayout(frc_raf)
        self.widget.setLayout(genel_raflar)
        self.scroll.setWidget(self.widget)
        self.setCentralWidget(self.scroll)          